//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebisReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DebisReference.DebisHSServiceSoap")]
    public interface DebisHSServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AkilliKartGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AkilliKartGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LDAPGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> LDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KutuphaneLDAPGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> KutuphaneLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SempozyumLDAPGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DebisReference.LDAPSonuc> SempozyumLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YoklamaLDAPGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DebisReference.YoklamaLDAPSonuc> YoklamaLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HarcamaLimitTakipLDAPGirisKontrolu", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DebisReference.HarcamaLimitTakipLDAPSonuc> HarcamaLimitTakipLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class LDAPSonuc
    {
        public bool Sonuc;
        public string Mesaj;
        public string AdSoyad;
        public string Email;
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class YoklamaLDAPSonuc
    {
        public bool Sonuc;
        public string Mesaj;
        public string AdSoyad;
        public string Email;
        public string Unvan;
        public string Bolum;
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class HarcamaLimitTakipLDAPSonuc
    {
        public bool Sonuc;
        public string Mesaj;
        public string AdSoyad;
        public string Email;
        public string PersonelNo;
        public string Bolum;
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DebisReference.DebisHSServiceSoap")]
    public interface DebisHSServiceSoapChannel : DebisReference.DebisHSServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DebisHSServiceSoapClient : System.ServiceModel.ClientBase<DebisReference.DebisHSServiceSoap>, DebisReference.DebisHSServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DebisHSServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DebisHSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), DebisHSServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebisHSServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DebisHSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DebisHSServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DebisHSServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public System.Threading.Tasks.Task<string> AkilliKartGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.AkilliKartGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public System.Threading.Tasks.Task<bool> LDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.LDAPGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public System.Threading.Tasks.Task<bool> KutuphaneLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.KutuphaneLDAPGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public System.Threading.Tasks.Task<DebisReference.LDAPSonuc> SempozyumLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.SempozyumLDAPGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public System.Threading.Tasks.Task<DebisReference.YoklamaLDAPSonuc> YoklamaLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.YoklamaLDAPGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public System.Threading.Tasks.Task<DebisReference.HarcamaLimitTakipLDAPSonuc> HarcamaLimitTakipLDAPGirisKontroluAsync(string sistemKullanimSifresi, string kullaniciAdi, string sifre)
        {
            return base.Channel.HarcamaLimitTakipLDAPGirisKontroluAsync(sistemKullanimSifresi, kullaniciAdi, sifre);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebisHSServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DebisHSServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DebisHSServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://debishs.deu.edu.tr/DebisHSService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DebisHSServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://debishs.deu.edu.tr/DebisHSService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DebisHSServiceSoap,
            
            DebisHSServiceSoap12,
        }
    }
}