-- ==================================================
-- DEÜ DUYURU YÖNETİM SİSTEMİ - ORACLE DATABASE
-- 03_TABLES.sql - Tüm Ana Tablolar
-- ==================================================
-- Tüm sistem tablolarını oluşturur
-- Dosya yönetimi dahil unified script
-- ==================================================

PROMPT ========================================
PROMPT DEÜ Duyuru Sistemi - Tablolar Oluşturuluyor
PROMPT ========================================

-- =============================================
-- 1. ROLLER TABLOSU
-- =============================================
PROMPT 1. ROLLER tablosu oluşturuluyor...

CREATE TABLE ROLLER (
    ID NUMBER(5) DEFAULT SEQ_ROLLER.NEXTVAL PRIMARY KEY,
    ROL_KODU VARCHAR2(20) NOT NULL,
    ROL_ADI VARCHAR2(100) NOT NULL,
    ACIKLAMA VARCHAR2(500),
    YETKI_SEVIYESI NUMBER(2) NOT NULL, -- 1-10 arası, yüksek numara = daha fazla yetki
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UK_ROLLER_KOD UNIQUE (ROL_KODU),
    CONSTRAINT CK_ROLLER_AKTIF CHECK (AKTIF IN ('Y', 'N')),
    CONSTRAINT CK_ROLLER_YETKI CHECK (YETKI_SEVIYESI BETWEEN 1 AND 10)
);

-- =============================================
-- 2. KULLANICILAR TABLOSU
-- =============================================
PROMPT 2. KULLANICILAR tablosu oluşturuluyor...

CREATE TABLE KULLANICILAR (
    ID NUMBER(10) DEFAULT SEQ_KULLANICILAR.NEXTVAL PRIMARY KEY,
    ROL_ID NUMBER(5) NOT NULL, -- Foreign Key to ROLLER table
    KULLANICI_ADI VARCHAR2(100) NOT NULL,
    AD_SOYAD VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    DEPARTMAN VARCHAR2(100),
    UNVAN VARCHAR2(100),
    GOREV_YERI NUMBER(10) DEFAULT 0,
    GOREV_YERI_ADI VARCHAR2(200) DEFAULT 'REKTÖRLÜK', -- Görev yeri adı
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    SON_GIRIS_TARIHI DATE,
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UK_KULLANICILAR_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_KULLANICILAR_KULLANICI_ADI UNIQUE (KULLANICI_ADI),
    CONSTRAINT FK_KULLANICILAR_ROL FOREIGN KEY (ROL_ID) REFERENCES ROLLER(ID),
    CONSTRAINT CK_KULLANICILAR_AKTIF CHECK (AKTIF IN ('Y', 'N'))
);

-- =============================================
-- 3. SISTEM AYARLARI TABLOSU
-- =============================================
PROMPT 2. SISTEM_AYARLARI tablosu oluşturuluyor...

CREATE TABLE SISTEM_AYARLARI (
    ID NUMBER(10) DEFAULT SEQ_SISTEM_AYARLARI.NEXTVAL PRIMARY KEY,
    AYAR_KATEGORI VARCHAR2(50) NOT NULL,
    AYAR_ANAHTAR VARCHAR2(100) NOT NULL,
    AYAR_DEGER VARCHAR2(4000),
    GOREV_YERI NUMBER(10) DEFAULT 0,
    AYAR_ACIKLAMA VARCHAR2(500),
    GIZLI CHAR(1) DEFAULT 'N' NOT NULL, -- 'Y' veya 'N'
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UK_SISTEM_AYARLARI UNIQUE (AYAR_KATEGORI, AYAR_ANAHTAR),
    CONSTRAINT CK_SISTEM_AYARLARI_GIZLI CHECK (GIZLI IN ('Y', 'N')),
    CONSTRAINT CK_SISTEM_AYARLARI_AKTIF CHECK (AKTIF IN ('Y', 'N'))
);

-- =============================================
-- 3. EPOSTA GRUPLARI TABLOSU
-- =============================================
PROMPT 3. EPOSTA_GRUPLARI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_GRUPLARI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_GRUPLARI.NEXTVAL PRIMARY KEY,
    GRUP_ADI VARCHAR2(100) NOT NULL,
    ACIKLAMA VARCHAR2(500),
    GRUP_TIPI VARCHAR2(20) NOT NULL, -- 'NORMAL', 'STATIK', 'DINAMIK', 'DEBIS'
    VIEW_ADI VARCHAR2(100), -- DINAMIK/STATIK gruplar için view/dosya adı
    FILTER_KOSULU VARCHAR2(500), -- DINAMIK gruplar için WHERE koşulu
    LISTECI_EMAIL VARCHAR2(200), -- DEBIS gruplar için listeci email adresi
    UYE_SAYISI NUMBER(10) DEFAULT 0 NOT NULL, -- Grup üye sayısı (trigger/backend tarafından güncellenir)
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UK_EPOSTA_GRUPLARI_AD UNIQUE (GRUP_ADI),
    CONSTRAINT CK_GRUP_TIPI CHECK (GRUP_TIPI IN ('NORMAL', 'STATIK', 'DINAMIK', 'DEBIS')),
    CONSTRAINT CK_EPOSTA_GRUPLARI_AKTIF CHECK (AKTIF IN ('Y', 'N'))
);

-- =============================================
-- 4. EPOSTA GRUP UYELERI TABLOSU
-- =============================================
PROMPT 4. EPOSTA_GRUP_UYELERI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_GRUP_UYELERI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_GRUP_UYELERI.NEXTVAL PRIMARY KEY,
    GRUP_ID NUMBER(10) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    AD_SOYAD VARCHAR2(200),
    DEPARTMAN VARCHAR2(100), -- Departman bilgisi
    DURUM VARCHAR2(20) DEFAULT 'AKTIF' NOT NULL, -- 'AKTIF', 'PASIF', 'IPTAL'
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    EKLENME_TARIHI DATE DEFAULT SYSDATE NOT NULL, -- Gruba eklenme tarihi
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT FK_GRUP_UYELERI_GRUP FOREIGN KEY (GRUP_ID) REFERENCES EPOSTA_GRUPLARI(ID),
    CONSTRAINT UK_GRUP_UYELERI UNIQUE (GRUP_ID, EMAIL),
    CONSTRAINT CK_GRUP_UYELERI_DURUM CHECK (DURUM IN ('AKTIF', 'PASIF', 'IPTAL'))
);

-- =============================================
-- 5. EPOSTA_SABLON_KATEGORILERI TABLOSU
-- =============================================
PROMPT 5. EPOSTA_SABLON_KATEGORILERI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_SABLON_KATEGORILERI (
    ID NUMBER DEFAULT SEQ_SABLON_KATEGORILERI.NEXTVAL PRIMARY KEY,
    KATEGORI_ADI VARCHAR2(100) NOT NULL,
    ACIKLAMA VARCHAR2(500),
    RENK VARCHAR2(7) DEFAULT '#1976d2', -- Hex renk kodu
    IKON VARCHAR2(50) DEFAULT 'label', -- Material icon adı
    SIRA_NO NUMBER DEFAULT 0,
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL CHECK (AKTIF IN ('Y', 'N')),
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE
);

-- =============================================
-- 6. EPOSTA SABLONLARI TABLOSU
-- =============================================
PROMPT 6. EPOSTA_SABLONLARI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_SABLONLARI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_SABLONLARI.NEXTVAL PRIMARY KEY,
    KATEGORI_ID NUMBER NOT NULL,
    SABLON_ADI VARCHAR2(100) NOT NULL,
    KONU_SABLONU VARCHAR2(500),
    ICERIK_SABLONU CLOB,
    VARSAYILAN CHAR(1) DEFAULT 'N' NOT NULL, -- 'Y' veya 'N'
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT UK_EPOSTA_SABLONLARI_AD UNIQUE (SABLON_ADI),
    CONSTRAINT CK_EPOSTA_SABLONLARI_VARSAYILAN CHECK (VARSAYILAN IN ('Y', 'N')),
    CONSTRAINT CK_EPOSTA_SABLONLARI_AKTIF CHECK (AKTIF IN ('Y', 'N')),
    -- FIX: ON DELETE SET NULL kaldırıldı (KATEGORI_ID NOT NULL olduğu için çelişki yaratıyordu)
    -- Şimdi: Kategori silinirken şablon varsa ORA-02292 hatası verir (veri bütünlüğü korunur)
    CONSTRAINT FK_SABLON_KATEGORI FOREIGN KEY (KATEGORI_ID) REFERENCES EPOSTA_SABLON_KATEGORILERI(ID)
);

-- =============================================
-- 7. DOSYALAR TABLOSU (File Management)
-- =============================================
PROMPT 7. DOSYALAR tablosu oluşturuluyor...

CREATE TABLE DOSYALAR (
    ID NUMBER(10) DEFAULT SEQ_DOSYALAR.NEXTVAL PRIMARY KEY,
    DUYURU_ID NUMBER(10), -- NULL olabilir (önce dosya yüklenip sonra duyuruya bağlanabilir)
    YUKLEYEN_KULLANICI_ID NUMBER(10) NOT NULL,
    SESSION_ID VARCHAR2(100), -- Geçici dosyalar için oturum ID'si
    DOSYA_ADI VARCHAR2(255) NOT NULL, -- Orijinal dosya adı
    DOSYA_YOLU VARCHAR2(500) NOT NULL, -- Sunucudaki fiziksel path
    DOSYA_TIPI VARCHAR2(100) NOT NULL, -- MIME type (image/jpeg, application/pdf, etc.)
    DOSYA_KATEGORISI VARCHAR2(50) DEFAULT 'ATTACHMENT' NOT NULL, -- ATTACHMENT, INLINE_IMAGE, BANNER
    DOSYA_BOYUTU NUMBER(12) NOT NULL, -- Byte cinsinden dosya boyutu
    DOSYA_HASH VARCHAR2(64), -- Dosya bütünlüğü kontrolü için MD5/SHA hash
    ACIKLAMA VARCHAR2(500), -- Dosya açıklaması
    AKTIF CHAR(1) DEFAULT 'Y' NOT NULL, -- 'Y' veya 'N'
    YUKLEME_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT FK_DOSYALAR_YUKLEYEN FOREIGN KEY (YUKLEYEN_KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT CK_DOSYALAR_AKTIF CHECK (AKTIF IN ('Y', 'N')),
    CONSTRAINT CK_DOSYA_KATEGORISI CHECK (DOSYA_KATEGORISI IN ('ATTACHMENT', 'INLINE_IMAGE', 'BANNER')),
    CONSTRAINT UK_DOSYALAR_DUYURU_HASH UNIQUE (DUYURU_ID, DOSYA_HASH)
);

-- =============================================
-- 8. EPOSTA DUYURULARI TABLOSU
-- =============================================
PROMPT 8. EPOSTA_DUYURULARI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_DUYURULARI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_DUYURULARI.NEXTVAL PRIMARY KEY,
    KONU VARCHAR2(500) NOT NULL,
    ICERIK CLOB NOT NULL, -- HTML içerik (email) veya Plain Text (sosyal medya)
    ACIKLAMA VARCHAR2(1000), -- Duyuru açıklaması (EDITOR tarafından doldurulur, Kontrolör/manager için bilgi)
    ICERIK_TIPI VARCHAR2(30) DEFAULT 'EMAIL' NOT NULL, -- EMAIL, SOSYAL_MEDYA_X, SOSYAL_MEDYA_FACEBOOK, SOSYAL_MEDYA_INSTAGRAM
    DUYURU_KATEGORISI VARCHAR2(50) DEFAULT 'GENEL_DUYURU_IMZASIZ' NOT NULL, -- Duyuruya imza eklemek için kategori
    GONDERICI_KATEGORI VARCHAR2(50) DEFAULT 'EMAIL_DUYURU' NOT NULL, -- SMTP gönderici kategorisi (EMAIL_DUYURU, EMAIL_REKTOR, etc.) - Hangi email hesabından gönderileceğini belirler
    DURUM VARCHAR2(30) DEFAULT 'TASLAK' NOT NULL, -- TASLAK, ILK_ONAY_BEKLIYOR, SON_ONAY_BEKLIYOR, REDDEDILDI, ONAYLANDI, GONDERILDI, IPTAL
    OLUSTURAN_KULLANICI_ID NUMBER(10) NOT NULL,
    ILK_ONAYLAYAN_KULLANICI_ID NUMBER(10), -- Koordinatör (ilk onaylayan)
    SON_ONAYLAYAN_KULLANICI_ID NUMBER(10), -- Manager (son onaylayan)    
    SABLON_ID NUMBER(10),
    BANNER_DOSYA_ID NUMBER(10), -- Ana banner/resim dosyası
    GERCEK_GONDERIM_TARIHI DATE, -- Gerçek gönderim tarihi (sadece EMAIL için)
    TOPLAM_ALICI_SAYISI NUMBER(8) DEFAULT 0, -- Sadece EMAIL için
    BASARILI_GONDERIM_SAYISI NUMBER(8) DEFAULT 0, -- Sadece EMAIL için
    BASARISIZ_GONDERIM_SAYISI NUMBER(8) DEFAULT 0, -- Sadece EMAIL için
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    CONSTRAINT FK_DUYURU_SABLON FOREIGN KEY (SABLON_ID) REFERENCES EPOSTA_SABLONLARI(ID),
    CONSTRAINT FK_DUYURU_OLUSTURAN FOREIGN KEY (OLUSTURAN_KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT FK_DUYURU_ILK_ONAYLAYAN FOREIGN KEY (ILK_ONAYLAYAN_KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT FK_DUYURU_SON_ONAYLAYAN FOREIGN KEY (SON_ONAYLAYAN_KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT FK_DUYURU_BANNER FOREIGN KEY (BANNER_DOSYA_ID) REFERENCES DOSYALAR(ID) ON DELETE SET NULL,
    CONSTRAINT CK_DUYURU_DURUM CHECK (DURUM IN ('TASLAK', 'ILK_ONAY_BEKLIYOR', 'SON_ONAY_BEKLIYOR', 'REDDEDILDI', 'ONAYLANDI', 'GONDERILIYOR', 'GONDERILDI', 'IPTAL')),
    CONSTRAINT CK_DUYURU_ICERIK_TIPI CHECK (ICERIK_TIPI IN ('EMAIL', 'SOSYAL_MEDYA'))
);

-- DOSYALAR tablosuna DUYURU_ID foreign key'ini ekle (circular reference'den kaçınmak için)
ALTER TABLE DOSYALAR ADD CONSTRAINT FK_DOSYALAR_DUYURU 
    FOREIGN KEY (DUYURU_ID) REFERENCES EPOSTA_DUYURULARI(ID) ON DELETE SET NULL;

-- =============================================
-- 9. EPOSTA DUYURU HAREKETLERI TABLOSU (Audit Trail)
-- =============================================
PROMPT 9. EPOSTA_DUYURU_HAREKETLERI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_DUYURU_HAREKETLERI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_DUYURU_HAREKETLERI.NEXTVAL PRIMARY KEY,
    DUYURU_ID NUMBER(10) NOT NULL,
    ONCEKI_DURUM VARCHAR2(30), -- NULL olabilir (ilk oluşturma)
    YENI_DURUM VARCHAR2(30) NOT NULL,
    ISLEM_TIPI VARCHAR2(30) NOT NULL, -- OLUSTURMA, ONAYA_GONDERME, ONAYLAMA, REDDETME, IPTAL, GONDERIM, DUZENLEME, SILME
    KULLANICI_ID NUMBER(10), -- NULL olabilir (sistem işlemleri için)
    ACIKLAMA VARCHAR2(500), -- Onay/Red notu
    SECILEN_ONAYLAYICI_ID NUMBER(10), -- Kontrolörün seçtiği manager ID'si (sadece ONAYLAMA işleminde)
    ISLEM_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_HAREKET_DUYURU FOREIGN KEY (DUYURU_ID) REFERENCES EPOSTA_DUYURULARI(ID) ON DELETE CASCADE,
    CONSTRAINT FK_HAREKET_KULLANICI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT FK_HAREKET_ONAYLAYICI FOREIGN KEY (SECILEN_ONAYLAYICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT CK_HAREKET_ISLEM_TIPI CHECK (ISLEM_TIPI IN ('OLUSTURMA', 'ONAYA_GONDERME', 'ONAYLAMA', 'REDDETME', 'IPTAL', 'GONDERIM', 'DUZENLEME', 'SILME'))
);

-- =============================================
-- 10. EPOSTA DUYURU ALICILARI TABLOSU
-- =============================================
PROMPT 10. EPOSTA_DUYURU_ALICILARI tablosu oluşturuluyor...

CREATE TABLE EPOSTA_DUYURU_ALICILARI (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_DUYURU_ALICILARI.NEXTVAL PRIMARY KEY,
    DUYURU_ID NUMBER(10) NOT NULL,
    GRUP_ID NUMBER(10), -- NULL ise manuel email
    ALICI_TIPI VARCHAR2(20) DEFAULT 'GRUP' NOT NULL, -- 'GRUP' veya 'MANUEL'
    ALICI_KATEGORISI VARCHAR2(10) DEFAULT 'BCC' NOT NULL, -- 'TO', 'CC', 'BCC'
    EMAIL VARCHAR2(200), -- GRUP için NULL olabilir, MANUEL için zorunlu
    AD_SOYAD VARCHAR2(200),
    GONDERIM_DURUMU VARCHAR2(20) DEFAULT 'BEKLIYOR' NOT NULL, -- 'BEKLIYOR', 'GONDERILDI', 'BASARISIZ', 'IPTAL'
    HATA_MESAJI VARCHAR2(500),
    GONDERIM_TARIHI DATE,
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_DUYURU_ALICI_DUYURU FOREIGN KEY (DUYURU_ID) REFERENCES EPOSTA_DUYURULARI(ID) ON DELETE CASCADE,
    CONSTRAINT FK_DUYURU_ALICI_GRUP FOREIGN KEY (GRUP_ID) REFERENCES EPOSTA_GRUPLARI(ID),
    CONSTRAINT CK_DUYURU_ALICI_TIPI CHECK (ALICI_TIPI IN ('GRUP', 'MANUEL')),
    CONSTRAINT CK_DUYURU_ALICI_KATEGORISI CHECK (ALICI_KATEGORISI IN ('TO', 'CC', 'BCC')),
    CONSTRAINT CK_DUYURU_GONDERIM_DURUMU CHECK (GONDERIM_DURUMU IN ('BEKLIYOR', 'GONDERILDI', 'BASARISIZ', 'IPTAL')),
    -- Alıcı tipi validasyonu: GRUP için GRUP_ID gerekli ve EMAIL NULL, MANUEL için EMAIL gerekli ve GRUP_ID NULL
    CONSTRAINT CK_Recipient_Type_Valid CHECK (
        (ALICI_TIPI = 'GRUP' AND GRUP_ID IS NOT NULL AND EMAIL IS NULL) OR
        (ALICI_TIPI = 'MANUEL' AND GRUP_ID IS NULL AND EMAIL IS NOT NULL)
    )
);

-- =============================================
-- 11. EPOSTA DUYURU ZAMANLAMALARI TABLOSU
-- =============================================
PROMPT 11. EPOSTA_DUYURU_ZAMANLAMALAR tablosu oluşturuluyor...

CREATE TABLE EPOSTA_DUYURU_ZAMANLAMALAR (
    ID NUMBER(10) DEFAULT SEQ_EPOSTA_DUYURU_ZAMANLAMALAR.NEXTVAL PRIMARY KEY,
    DUYURU_ID NUMBER(10) NOT NULL,
    ZAMANLANAN_TARIH DATE NOT NULL,
    DURUM VARCHAR2(50) DEFAULT 'BEKLEMEDE' NOT NULL, -- 'BEKLEMEDE', 'GONDERILDI', 'IPTAL', 'HATA'
    GONDERIM_TARIHI DATE,
    HANGFIRE_JOB_ID VARCHAR2(200), -- Hangfire job ID - iptal işlemi için
    HATA_MESAJI VARCHAR2(1000),
    ALICI_SAYISI NUMBER(8) DEFAULT 0,
    OLUSTURAN_KULLANICI_ID NUMBER(10) NOT NULL,
    OLUSTURMA_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    GUNCELLEME_TARIHI DATE,
    IPTAL_NOTU VARCHAR2(500),
    CONSTRAINT FK_ZAMANLAMA_DUYURU FOREIGN KEY (DUYURU_ID) REFERENCES EPOSTA_DUYURULARI(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ZAMANLAMA_OLUSTURAN FOREIGN KEY (OLUSTURAN_KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT CK_ZAMANLAMA_DURUM CHECK (DURUM IN ('BEKLEMEDE', 'GONDERILDI', 'IPTAL', 'HATA'))
);

-- =============================================
-- 12. EPOSTA DUYURU GONDERIM LOG TABLOSU
-- =============================================
PROMPT 12. EPOSTA_DUYURU_GONDERIM_LOG tablosu oluşturuluyor...

CREATE TABLE EPOSTA_DUYURU_GONDERIM_LOG (
    ID NUMBER(10) DEFAULT SEQ_DUYURU_GONDERIM_LOG.NEXTVAL PRIMARY KEY,
    DUYURU_ID NUMBER(10) NOT NULL,
    ALICI_ID NUMBER(10), -- EpostaDuyuruAlici tablosundaki ID (opsiyonel)
    ALICI_EMAIL VARCHAR2(254) NOT NULL,
    ALICI_AD_SOYAD VARCHAR2(100),
    ALICI_KATEGORISI VARCHAR2(10) NOT NULL, -- 'TO', 'CC', 'BCC'
    GONDERIM_DURUMU VARCHAR2(20) NOT NULL, -- 'BASARILI', 'BASARISIZ'
    HATA_MESAJI VARCHAR2(1000),
    GONDERIM_TARIHI DATE DEFAULT SYSDATE NOT NULL,    
    CONSTRAINT FK_GONDERIM_LOG_DUYURU FOREIGN KEY (DUYURU_ID) REFERENCES EPOSTA_DUYURULARI(ID) ON DELETE CASCADE,
    CONSTRAINT FK_GONDERIM_LOG_ALICI FOREIGN KEY (ALICI_ID) REFERENCES EPOSTA_DUYURU_ALICILARI(ID) ON DELETE SET NULL,
    CONSTRAINT CK_GONDERIM_LOG_KATEGORI CHECK (ALICI_KATEGORISI IN ('TO', 'CC', 'BCC')),
    CONSTRAINT CK_GONDERIM_LOG_DURUM CHECK (GONDERIM_DURUMU IN ('BASARILI', 'BASARISIZ'))
);

-- =============================================
-- 13. LOG TABLOLARI
-- =============================================
PROMPT 13. LOG tabloları oluşturuluyor...

-- Login Log Tablosu
CREATE TABLE LOG_LOGIN (
    ID NUMBER(10) DEFAULT SEQ_LOG_LOGIN.NEXTVAL PRIMARY KEY,
    KULLANICI_ID NUMBER(10),
    KULLANICI_ADI VARCHAR2(100),
    EMAIL VARCHAR2(200),
    IP_ADRES VARCHAR2(45), -- IPv6 support
    USER_AGENT VARCHAR2(500),
    GIRIS_TURU VARCHAR2(20) NOT NULL, -- 'LDAP', 'SSO', 'API'
    BASARILI CHAR(1) NOT NULL, -- 'Y' veya 'N'
    HATA_MESAJI VARCHAR2(500),
    GIRIS_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LOG_LOGIN_KULLANICI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT CK_LOG_LOGIN_BASARILI CHECK (BASARILI IN ('Y', 'N')),
    CONSTRAINT CK_LOG_LOGIN_GIRIS_TURU CHECK (GIRIS_TURU IN ('LDAP', 'SSO', 'API'))
);

-- Sistem Log Tablosu
CREATE TABLE LOG_SISTEM (
    ID NUMBER(10) DEFAULT SEQ_LOG_SISTEM.NEXTVAL PRIMARY KEY,
    KULLANICI_ID NUMBER(10),
    LOG_SEVIYE VARCHAR2(10) NOT NULL, -- 'ERROR', 'WARN', 'INFO', 'DEBUG'
    KATEGORI VARCHAR2(50) NOT NULL, -- 'EMAIL', 'USER', 'GROUP', 'FILE', 'SYSTEM'
    ISLEM VARCHAR2(100) NOT NULL,
    DETAY CLOB,
    IP_ADRES VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    LOG_TARIHI DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_LOG_SISTEM_KULLANICI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICILAR(ID),
    CONSTRAINT CK_LOG_SISTEM_SEVIYE CHECK (LOG_SEVIYE IN ('ERROR', 'WARN', 'INFO', 'DEBUG')),
    CONSTRAINT CK_LOG_SISTEM_KATEGORI CHECK (KATEGORI IN ('EMAIL', 'USER', 'GROUP', 'FILE', 'SYSTEM'))
);

COMMIT;

PROMPT ========================================
PROMPT Tablolar başarıyla oluşturuldu
PROMPT ========================================

-- Kontrol sorguları
PROMPT Oluşturulan tablolar:
SELECT table_name, num_rows
FROM user_tables
WHERE table_name IN ('ROLLER', 'KULLANICILAR', 'EPOSTA_GRUPLARI', 'EPOSTA_GRUP_UYELERI',
                     'EPOSTA_SABLONLARI', 'EPOSTA_DUYURULARI', 'EPOSTA_DUYURU_HAREKETLERI', 'EPOSTA_DUYURU_ALICILARI',
                     'EPOSTA_DUYURU_ZAMANLAMALAR', 'EPOSTA_DUYURU_GONDERIM_LOG', 'DOSYALAR', 'SISTEM_AYARLARI',
                     'LOG_LOGIN', 'LOG_SISTEM')
ORDER BY table_name;

SELECT 'TABLES script completed successfully' AS STATUS FROM DUAL;